### ISSUE TITLE
サイトの背景を決める

### ISSUE THREAD

**Issue by Wachankoushiki** [Wachankoushiki/team-project#1]
サイトの背景にふさわしい写真を著作権に気を付けてネットから探してきてください

**Comment by s1F10240242** [comment]
![converted](https://github.com/Wachankoushiki/team-project/assets/172235459/f008ad31-45ea-484f-8a2f-f3f109310e85)
こんなのはどうでしょう

**Comment by Wachankoushiki** [comment]
ありがとうございます

**Comment by Wachankoushiki** [comment]
おつかれさまでした
